server:
  port: 8756
spring:
  datasource:
    url: jdbc:mysql://192.168.31.58:3306/lx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MiSS*+520
    driver-class-name: com.mysql.jdbc.Driver

